#### general settings
name: ecdb
use_tb_logger: true
model: denoising
distortion: inpaint
gpu_ids: [0]
stage: train

sde:
  lambda_square: 30
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005

degradation:
  # for inpainting
  mask_root: 
  
#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: GT
    dataroot_GT: 

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 8
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Val_Dataset
    mode: GT
    dataroot_GT: 


#### network structures
network_G:
  which_model_G: ControlConditional
  setting:
    in_nc: 3
    out_nc: 3
    nf: 64
    depth: 4

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  optimizer: Adam # Adam, AdamW, Lion
  lr_G: !!float 2e-5
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 500000
  warmup_iter: -1  # no warm up
  lr_steps: [100000, 200000, 300000, 400000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 10000

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2e4

unet_pretrained: path_to_pretrained_goub_inpainting.pth